export default [
	{
		id: 1,
		project: "Project 1",
		title: "Basquetball ScoreBoard",
		image: "project1.webp",
		link: "https://basquetball-scoreboard.netlify.app/",
		description:"Used JS Vanilla tags such as DOM, functions , loops and arrays.",	
	},
	{
		id: 2,
		project: "Project 2",
		title: "Password Generator",
		image: "project2.webp",
		link:"https://password-generator-xyz.netlify.app/",
		description: "Used JS Vanilla tags such as math functions, DOM and arrays.",
	},
	{
		id: 3,
		project: "Project 3",
		title: "Unit Converter",
		image: "project3.webp",
		link:"https://unit-converterjs.netlify.app/",
		description:"Used JS Vanilla sucha as if condition, math functions, operators , operations, DOM.",	
	},
	{
		id: 4,
		project: "Project 4",
		title: "GPT Gift Generator",
		image: "project4.webp",
		link:"https://gpt-gift-generator.vercel.app",
		description:"Used ReactJS Hooks such as UseStae UseEffect UseRef API in order to make a GPT form project.",	
	},
	{
		id: 5,
		project: "Project 5",
		title: "Landing Page Design - Tailwind CSS",
		image: "project5.webp",
		link:"https://tailwindcss-scrimba.netlify.app/",
		description:"Used TailwindCSS in order tom make fronted design faster.",	
	},
	{
		id: 6,
		project: "Project 6",
		title: "AJUL - Blog Website",
		image: "project6.webp",
		link:"https://ajul.vercel.app",
		description:"Used Next.JS side rendering - ReactJS Hooks, TailwindCSS, GraphQL mutations and HyGraphAPI.",	
	},
	{
		id: 7,
		project: "Project 7",
		title: "C-Art & Studios - Ecommerce",
		link:"https://c-art-studios.vercel.app",
		image: "project7.webp",
		description:"Next.js Ecommerce in which I complemented ReactJS Hooks, TailwindCSS and MongoDB",	
	},
]